name = "music-website"
compatibility_date = "2023-10-01"
pages_build_output_dir = "./public"

[env.production]
TELEGRAM_BOT_TOKEN = "7548100323:AAH74u2x5bX-kSZxapNnUPnwZzs0lt5ugZI"
TELEGRAM_CHAT_ID = "661777187"

[[functions]]
name = "upload"
path = "./functions/telegram.js"

[[functions]]
name = "files"
path = "./functions/files.js"
